service: jokes

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: us-east-1
  memorySize: 128
  timeout: 30
  deploymentBucket: lungo-iac-files
  tags: # Optional service wide function tags
    Environment: JOKES
    Environment_Type: JOKES-API

package:
  exclude:
    - src/**
    - .env
    - nodemon.json
    - tsconfig.json
    - .serverless
    - .vscode

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: jokes-api.eduardozuchetti.com.br
    # basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false

functions:
  api:
    handler: build/index.handler
    environment:
      MONGO_DB_URI: mongodb+srv://appUser:mQlnAuNuswxvEB9S@cluster-dev-o4hm3.gcp.mongodb.net/jokes
    events: 
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true