version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  build:
    jobs:
      - build
  deploy:
    jobs:
      - deploy-dev

jobs:
  build:
    docker:
      - image: circleci/node:12.19
    steps:
    - checkout
    - run:
        name: update-npm
        command: sudo npm install -g npm@6
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: install-npm-dependencies
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
    - run:
        name: build-sources
        command: npm run build
    - save_cache:
        key: dependency-cache-build
        paths:
          - ./build
          
  deploy-dev:
    docker:
      - image: circleci/node:12.19
    steps:
      - checkout
      - run:
          name: install-serverless
          command: sudo npm install -g serverless@2
      - run:
          name: configure-serverless
          command: serverless config --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: dependency-cache-build
      - run:
          name: serverless-deploy
          command: serverless deploy --stage ${STAGE}
